export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST ='SIGNUP_REQUEST';
export const SIGNUP_SUCCESS ='SIGNUP_SUCCESS';
export const SIGNUP_FAILURE ='SIGNUP_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT = "LOGOUT";

export const LOGIN_RESETPAYLOAD ='LOGIN_RESETPAYLOAD';
export const SIGNUP_RESETPAYLOAD ='SIGNUP_RESETPAYLOAD';

export const SEARCH_REQUEST ='SEARCH_REQUEST';
export const SEARCH_SUCCESS ='SEARCH_SUCCESS';
export const SEARCH_FAILURE ='SEARCH_FAILURE';

export const GET_SEARCHPARAMS = 'GET_SEARCHPARAMS';
export const UPDATE_PROPERTYINDEX = 'UPDATE_PROPERTYINDEX';
export const RESET_PROPERTYDATA= 'RESET_PROPERTYDATA';